filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/soundmanager2*'
        - 'js/bar*'
        - 'js/berniecode*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 60 # Timeout in seconds. 120 minutes
