build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]

filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/soundmanager2*'
        - 'js/bar*'
        - 'js/sharing/berniecode*'
        - 'js/jquery*'
        - 'js/sharing/360player*'          

imports:
    - javascript
    - php
